apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-one-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-one-pod
  template:
    metadata:
      labels:
        app: microservice-one-pod
    spec:
      containers:
      - name: microservice-one-container
        image: primero21/microservicio-one:v1
        ports:
        - containerPort: 8090
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: qa
        - name: TZ
          value: America/Mexico_City
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-one-svc
spec:
  selector:
    app: microservice-one-pod
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  type: LoadBalancer