apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc
config:
  discovery: http://192.168.1.137:8070/auth/realms/master/.well-known/openid-configuration
  client_id: kong
  client_secret: 4de585cc-33fe-41e1-90c5-568ccb89e790
  realm: master
  introspection_endpoint: http://192.168.1.137:8070/auth/realms/master/protocol/openid-connect/token/introspect
plugin: oidc